<?php

/**
 * Implements hook_theme().
 */
function tmt_eu_cookie_compliance_theme($existing, $type, $theme, $path) {
  return [
    'tmt_eu_cookie_compliance_toggle' => [
      'variables' => [
        'label' => '',
        'classes' => [],
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments_alter().
 */
function tmt_eu_cookie_compliance_page_attachments_alter(array &$page) {
  // Attach the session management script on every page.
  $page['#attached']['library'][] = 'tmt_eu_cookie_compliance/session';
}
